package myetesta.language.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptBAssertStatement = createDescriptorForBAssertStatement();
  /*package*/ final ConceptDescriptor myConceptBEmpytySuite = createDescriptorForBEmpytySuite();
  /*package*/ final ConceptDescriptor myConceptBExecuteSingleTestCase = createDescriptorForBExecuteSingleTestCase();
  /*package*/ final ConceptDescriptor myConceptBExecuteTests = createDescriptorForBExecuteTests();
  /*package*/ final ConceptDescriptor myConceptBTestCase = createDescriptorForBTestCase();
  /*package*/ final ConceptDescriptor myConceptBTestSuite = createDescriptorForBTestSuite();
  /*package*/ final ConceptDescriptor myConceptBTestSuiteParent = createDescriptorForBTestSuiteParent();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, "mybasica");
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.aggregatedLanguage(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, "mybasica");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBAssertStatement, myConceptBEmpytySuite, myConceptBExecuteSingleTestCase, myConceptBExecuteTests, myConceptBTestCase, myConceptBTestSuite, myConceptBTestSuiteParent);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.BAssertStatement:
        return myConceptBAssertStatement;
      case LanguageConceptSwitch.BEmpytySuite:
        return myConceptBEmpytySuite;
      case LanguageConceptSwitch.BExecuteSingleTestCase:
        return myConceptBExecuteSingleTestCase;
      case LanguageConceptSwitch.BExecuteTests:
        return myConceptBExecuteTests;
      case LanguageConceptSwitch.BTestCase:
        return myConceptBTestCase;
      case LanguageConceptSwitch.BTestSuite:
        return myConceptBTestSuite;
      case LanguageConceptSwitch.BTestSuiteParent:
        return myConceptBTestSuiteParent;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForBAssertStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("myetesta.language", "BAssertStatement", 0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x7aea2d0de96dfeb7L);
    b.class_(false, false, false);
    // extends: mybasica.structure.BStatement
    b.super_(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, 0x7aeac81c0f662deeL);
    b.origin("r:16b8d083-9ad7-4e51-8947-d2314795510c(myetesta.language.structure)/8856941154951626423");
    b.version(3);
    b.aggregate("expr", 0x7aea2d0de97072a7L).target(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, 0x7aeac81c0f677b0cL).optional(false).ordered(true).multiple(false).origin("8856941154951787175").done();
    b.alias("assert");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBEmpytySuite() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("myetesta.language", "BEmpytySuite", 0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x679b735ccd32951eL);
    b.class_(false, false, false);
    // extends: myetesta.language.structure.BTestSuiteParent
    b.super_(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x679b735ccd430dfcL);
    b.origin("r:16b8d083-9ad7-4e51-8947-d2314795510c(myetesta.language.structure)/7465687649713558814");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBExecuteSingleTestCase() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("myetesta.language", "BExecuteSingleTestCase", 0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x679b735ccd235258L);
    b.class_(false, false, false);
    // extends: mybasica.structure.BStatement
    b.super_(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, 0x7aeac81c0f662deeL);
    b.origin("r:16b8d083-9ad7-4e51-8947-d2314795510c(myetesta.language.structure)/7465687649712558680");
    b.version(3);
    b.associate("test", 0x679b735ccd23525aL).target(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x3ddf8bbe6bd2850aL).optional(false).origin("7465687649712558682").done();
    b.associate("suite", 0x679b735ccd39dd5bL).target(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x3ddf8bbe6bd28507L).optional(false).origin("7465687649714036059").done();
    b.alias("execute test");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBExecuteTests() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("myetesta.language", "BExecuteTests", 0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x679b735ccd1d5ed3L);
    b.class_(false, false, false);
    // extends: mybasica.structure.BStatement
    b.super_(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, 0x7aeac81c0f662deeL);
    b.origin("r:16b8d083-9ad7-4e51-8947-d2314795510c(myetesta.language.structure)/7465687649712168659");
    b.version(3);
    b.associate("testSuite", 0x679b735ccd1d5ed5L).target(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x3ddf8bbe6bd28507L).optional(false).origin("7465687649712168661").done();
    b.alias("execute tests");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBTestCase() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("myetesta.language", "BTestCase", 0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x3ddf8bbe6bd2850aL);
    b.class_(false, false, false);
    // extends: myetesta.language.structure.BTestSuiteParent
    b.super_(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x679b735ccd430dfcL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, 0x7aea2d0de985155cL);
    b.origin("r:16b8d083-9ad7-4e51-8947-d2314795510c(myetesta.language.structure)/4458435806089086218");
    b.version(3);
    b.aggregate("content", 0x3ddf8bbe6bd9a8e7L).target(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, 0x7aeac81c0f662deeL).optional(true).ordered(true).multiple(true).origin("4458435806089554151").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBTestSuite() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("myetesta.language", "BTestSuite", 0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x3ddf8bbe6bd28507L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:16b8d083-9ad7-4e51-8947-d2314795510c(myetesta.language.structure)/4458435806089086215");
    b.version(3);
    b.aggregate("tests", 0x3ddf8bbe6bd28815L).target(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x679b735ccd430dfcL).optional(true).ordered(true).multiple(true).origin("4458435806089086997").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBTestSuiteParent() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("myetesta.language", "BTestSuiteParent", 0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x679b735ccd430dfcL);
    b.class_(false, true, false);
    b.origin("r:16b8d083-9ad7-4e51-8947-d2314795510c(myetesta.language.structure)/7465687649714638332");
    b.version(3);
    return b.create();
  }
}
