package complex.datatypes.language.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BaseEntityMember = 0;
  public static final int EmptyEntityMember = 1;
  public static final int EntityDefinition = 2;
  public static final int EntityMember = 3;
  public static final int EntityType = 4;
  public static final int MySpecialEntityDefinition = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x7563d14a4ef54002L, 0xadf6eb0799115e60L);
    builder.put(0x27581bc554634929L, BaseEntityMember);
    builder.put(0x27581bc554634b3dL, EmptyEntityMember);
    builder.put(0x27581bc5546348b5L, EntityDefinition);
    builder.put(0x27581bc5546b93a2L, EntityMember);
    builder.put(0x3b289434f886aceaL, EntityType);
    builder.put(0x3bb1f2a967f91d10L, MySpecialEntityDefinition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
