package mybasica.test.typesystem;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.ClassRule;
import jetbrains.mps.lang.test.runtime.TestParametersCache;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseEditorTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

@MPSLaunch
public class AddScpecificTypeWorks_Test extends BaseTransformationTest {
  @ClassRule
  public static final TestParametersCache ourParamCache = new TestParametersCache(AddScpecificTypeWorks_Test.class, "/Users/aindamutsa/MPSProjects/mybasica", "r:d2add095-749f-4fbe-82d5-4923be229b2f(mybasica.test.typesystem@tests)", false);

  public AddScpecificTypeWorks_Test() {
    super(ourParamCache);
  }

  @Test
  public void test_AddScpecificTypeWorks() throws Throwable {
    new TestBody(this).testMethod();
  }

  /*package*/ static class TestBody extends BaseEditorTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    public void testMethodImpl() throws Exception {
      initEditorComponent("7465687649711788542", "7465687649711788645");
      invokeParameterizedIntention("mybasica.intentions.addSpecificType_Intention", CONCEPTS.BIntegerType$dw, myStart.getNode());
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept BIntegerType$dw = MetaAdapterFactory.getConcept(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, 0x3ddf8bbe6ba5e308L, "mybasica.structure.BIntegerType");
  }
}
