package mybasica.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import java.util.Set;
import jetbrains.mps.internal.collections.runtime.SetSequence;
import java.util.HashSet;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import mybasica.behavior.BStatementContainer__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;

public class check_duplicateVariableNames_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_duplicateVariableNames_NonTypesystemRule() {
  }
  public void applyRule(final SNode bStatementContainer, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    Set<String> varNames = SetSequence.fromSet(new HashSet<String>());
    for (SNode variable_ : SNodeOperations.ofConcept(BStatementContainer__BehaviorDescriptor.getStatements_id7FEbgRDHtJ4.invoke(bStatementContainer), CONCEPTS.BVariable$jk)) {
      if (SetSequence.fromSet(varNames).contains(SPropertyOperations.getString(variable_, PROPS.name$MnvL))) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(variable_, "duplicate name on variable: " + SPropertyOperations.getString(variable_, PROPS.name$MnvL), "r:623432a5-9cef-4769-8359-ee5e617f0f7a(mybasica.typesystem)", "4458435806083820284", null, errorTarget);
        }
      }
      SetSequence.fromSet(varNames).addElement(SPropertyOperations.getString(variable_, PROPS.name$MnvL));
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.BStatementContainer$L$;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept BVariable$jk = MetaAdapterFactory.getConcept(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, 0x7aeac81c0f662b2aL, "mybasica.structure.BVariable");
    /*package*/ static final SInterfaceConcept BStatementContainer$L$ = MetaAdapterFactory.getInterfaceConcept(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, 0x7aea2d0de985155cL, "mybasica.structure.BStatementContainer");
  }
}
