package mybasica.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class typeof_BVariableReference_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_BVariableReference_InferenceRule() {
  }
  public void applyRule(final SNode bVariableReference, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = bVariableReference;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:623432a5-9cef-4769-8359-ee5e617f0f7a(mybasica.typesystem)", "8856941154952608837", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:623432a5-9cef-4769-8359-ee5e617f0f7a(mybasica.typesystem)", "8856941154952607379", true), (SNode) typeCheckingContext.typeOf(SLinkOperations.getTarget(bVariableReference, LINKS.variable$QDW2), "r:623432a5-9cef-4769-8359-ee5e617f0f7a(mybasica.typesystem)", "8856941154952608853", true), _info_12389875345);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.BVariableReference$H2;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink variable$QDW2 = MetaAdapterFactory.getReferenceLink(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, 0x7aea2d0de9781aa3L, 0x7aea2d0de9781aa5L, "variable");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept BVariableReference$H2 = MetaAdapterFactory.getConcept(0x4893d0aba60e42bcL, 0xbfcd58191c291322L, 0x7aea2d0de9781aa3L, "mybasica.structure.BVariableReference");
  }
}
