package myetesta.language.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new BAssertStatement_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new BEmpytySuite_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new BExecuteSingleTestCase_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new BExecuteTests_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new BTestCase_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new BTestSuite_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new BEmpytySuite_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x7aea2d0de96dfeb7L), MetaIdFactory.conceptId(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x679b735ccd32951eL), MetaIdFactory.conceptId(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x679b735ccd235258L), MetaIdFactory.conceptId(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x679b735ccd1d5ed3L), MetaIdFactory.conceptId(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x3ddf8bbe6bd2850aL), MetaIdFactory.conceptId(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x3ddf8bbe6bd28507L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xe19d8a3c67da4363L, 0x8f44c6c0cab85e88L, 0x679b735ccd32951eL)).seal();
}
