package mybasica.sandbox;

/*Generated by MPS */


public class myTests {
  public static void name() {
    String arsene = "arsene";
    String arsenedksj = "dksjkfjsdkfj";
  }


  public static void hello() {
    String hi = "dshjfhsjd";
  }

  public static void runAll() {
    name();
    hello();
  }
}
