package mybasica.sandbox;

/*Generated by MPS */


public class SomeOtherTests {
  public static void name1() {
  }

  public static void name_1() {
  }
  public static void runAll() {
    name1();
    name_1();
  }
}
