package mybasica.sandbox;

/*Generated by MPS */


public class workbook {
  public static void Main() {
    int c = 1 + 22 - 2;
    int y = 10 + 1 * 1;
    String name = "some names";
    int x = c + y;
    boolean bool = 1 > 2;
SomeOtherTests.runAll()
<!TextGen not found for 'complex.datatypes.language.structure.EntityDefinition'!>
<!TextGen not found for 'complex.datatypes.language.structure.EntityDefinition'!>
  }
}
